# Build very simple java library with Maven, Open JDK 8

before_install:
  # Set Maven builder executable permissions
  - chmod +x mvnw

language: java
install: true
jdk: openjdk8

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
