# Build very simple java library with Maven, Open JDK 8

before_install:
  # Set Maven builder executable permissions
  - chmod +x mvnw

language: java
install: true
jdk: openjdk8

script:
  # the following command line runs the tests with coverage and builds the project
  - ./mvnw clean install
  # the following command line executes the SonarCloud analysis
  #- ./mvnw sonar:sonar
